Fixes #80 - adds a simple GH Actions workflow to build Apex Mocks on push and PR
apex-enterprise-patterns/fflib-apex-mocks pull request #101
Opened 2020-09-29 16:36 UTC by daveespo

2020-09-29 17:18 UTC, stohn777 requested changes

2020-09-29 17:18 UTC, stohn777 commented on .github/workflows/deploy.and.test.yml
> +        run: sfdx force:org:delete -p
@daveespo Here's what I've used before ...
```
-   name: Finalize
    if: always()
    run: sfdx force:org:delete -p -u $SCRATCH_ORG_NAME -v $DEV_HUB_NAME
```

2020-09-30 17:40 UTC, stohn777 approved these changes

2020-10-03 22:57 UTC, ImJohnMDaniel approved these changes

2020-10-03 22:57 UTC, merged