Devops/removal of fflib mocks
apex-enterprise-patterns/fflib-apex-mocks pull request #155
Opened 2024-11-30 18:17 UTC by ImJohnMDaniel

2024-12-01 21:36 UTC, stohn777 approved these changes

2024-12-02 14:38 UTC, daveespo requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/155)* status: all files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel)

___
*[`sfdx-source/apex-mocks/test/classes/fflib_ApexMocksTest.cls` line 723 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/155#-OD6nTKzAr_M-_GKS76d:-OD6nTKzAr_M-_GKS76e:b-yopbji) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/9cf40534f59905461cb8701051ee83618bd56635/sfdx-source/apex-mocks/test/classes/fflib_ApexMocksTest.cls#L723)):*
> ```vb6
> 		// Given
> 		fflib_ApexMocks mocks = new fflib_ApexMocks();
> 		// fflib_MyList.IList mockList = new fflib_Mocks.Mockfflib_MyList(mocks);
> ```

Why leave a commented-out line here? (and below)


<!-- Sent from Reviewable.io -->

2024-12-02 16:12 UTC, ImJohnMDaniel commented
> > Reviewed 4 of 4 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/155)_ status: all files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel)
> 
> _[`sfdx-source/apex-mocks/test/classes/fflib_ApexMocksTest.cls` line 723 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/155#-OD6nTKzAr_M-_GKS76d:-OD6nTKzAr_M-_GKS76e:b-yopbji) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/9cf40534f59905461cb8701051ee83618bd56635/sfdx-source/apex-mocks/test/classes/fflib_ApexMocksTest.cls#L723)):_
> 
> > ```vba
> > 		// Given
> > 		fflib_ApexMocks mocks = new fflib_ApexMocks();
> > 		// fflib_MyList.IList mockList = new fflib_Mocks.Mockfflib_MyList(mocks);
> > ```
> 
> Why leave a commented-out line here? (and below)

@daveespo -- Good catch.  I have removed the obsolete comments.  Cheers!

2024-12-02 17:04 UTC, stohn777 approved these changes

2024-12-02 17:11 UTC, merged